package com.tgam.hadoop.mapreduce;

/**
 * A record reader for splits generated by an Omniture hit_data.tsv daily data file.
 * @author Mike Sukmanowsky (<a href="mailto:mike.sukmanowsky@gmail.com">mike.sukmanowsky@gmail.com</a>)
 *
 */
public class OmnitureDataFileRecordReader353 extends OmnitureDataFileRecordReader {

    public static final int NUMBER_OF_FIELDS = 353;

    public OmnitureDataFileRecordReader353() {
        super(NUMBER_OF_FIELDS);
    }
}
