package com.tgam.hadoop.mapreduce;

/**
 * A record reader for splits generated by an Omniture hit_data.tsv daily data file.
 * @author Mike Sukmanowsky (<a href="mailto:mike.sukmanowsky@gmail.com">mike.sukmanowsky@gmail.com</a>)
 *
 */
public class OmnitureDataFileRecordReader554 extends OmnitureDataFileRecordReader {
	
	private static final int NUMBER_OF_FIELDS = 554;

    public OmnitureDataFileRecordReader554() {
        super(NUMBER_OF_FIELDS);
    }
	
}
